cache:
    paths:
    - make/.m2/repository
variables:
    MAVEN_CLI_OPTS: --quiet --batch-mode --settings make/.m2/settings.xml -Dmaven.repo.local=make/.m2/repository
    APIDOCS_ARTIFACT: target/apidocs
stages:
- validate
- test
- mvn_deploy
- publish_javadocs
check_style:
    stage: validate
    image: maven:3-jdk-11
    script:
    - mvn checkstyle:check -Dcheckstyle.config.location=google_checks.xml
    allow_failure: true
maven_test:
    stage: test
    image: maven:3-jdk-11
    script:
    - mvn ${MAVEN_CLI_OPTS} test -Dcheckstyle.skip
    artifacts:
        expire_in: 1 day
        reports:
            junit:
            - target/surefire-reports/TEST-*.xml
maven_deploy:
    stage: mvn_deploy
    image: maven:3-jdk-11
    script:
    - mvn deploy $MAVEN_CLI_OPTS -Dcheckstyle.skip -DskipTests
    - test -d ${APIDOCS_ARTIFACT}
    artifacts:
        expire_in: 1 day
        paths:
        - ${APIDOCS_ARTIFACT}
pages:
    stage: publish_javadocs
    image: alpine:latest
    before_script:
    - test -d ${APIDOCS_ARTIFACT}
    - rm -rf public  
    - mkdir public
    script:
    - echo "Publishing javadocs"
    - cp -r ${APIDOCS_ARTIFACT}/* public/.
    artifacts:
        expire_in: 1 day
        paths:
        - ${APIDOCS_ARTIFACT}
    only:
    - master