image: alpine:latest

stages:
  - check
  - pages


check code style:
  stage: check
  image: maven:3-jdk-11
  tags:
    - maven
  script:
    - echo "Checking Code Style"
    - mvn checkstyle:check -Dcheckstyle.config.location=google_checks.xml
  allow_failure: true


pages:
  stage: test
  script:
  - echo 'Nothing to do'
  artifacts:
    paths:
    - public
  only:
  - master
